<?php

/**
 * @file
 * Provides functionality and configuration for the Roomify Activity example content module.
 */

/**
 * Single day Activity.
 */
function roomify_activity_example_content_create_single_day_activity($images_folder) {
  $module_path = drupal_get_path('module', 'roomify_activity_example_content');

  $bat_type = bat_type_create(array(
    'type' => 'single_day_activity',
    'name' => 'Jet sky',
    'status' => 1,
    'bookable' => 1,
    'created' => REQUEST_TIME,
    'uid' => 1,
  ));

  $bat_type->activity_standard_duration[LANGUAGE_NONE][0] = array(
    'interval' => '15',
    'period' => 'minute',
  );
  $bat_type->activity_maximum_duration[LANGUAGE_NONE][0] = array(
    'interval' => '30',
    'period' => 'minute',
  );
  $bat_type->activity_opening_time[LANGUAGE_NONE][0] = array(
    'value' => 32400,
    'value2' => 61200,
    'mon' => 1,
    'tue' => 1,
    'wed' => 1,
    'thu' => 1,
    'fri' => 1,
    'sat' => 0,
    'sun' => 0.
  );
  $bat_type->activity_default_price[LANGUAGE_NONE][0] = array(
    'amount' => 2000,
    'currency_code' => 'USD',
  );

  $bat_type->save();

  for ($i = 1; $i <= 4; $i++) {
    $unit = bat_unit_create(array('type' => 'default'));
    $unit->name = $bat_type->name . ' ' . $i;
    $unit->created = REQUEST_TIME;

    $unit->type_id = $bat_type->type_id;
    $unit->default_state = 1;
    $unit->uid = $bat_type->uid;
    $unit->save();
  }

  $property_type = roomify_property_create(array(
    'type' => 'single_day_activity_property',
    'name' => 'Jet sky',
    'created' => REQUEST_TIME,
    'uid' => 1,
  ));

  // Property Description.
  $property_type->field_sp_description['en'][0]['value'] = 'This oceanfront home has an incredible view from its picture window. No streets to cross, just down the elevator to the beach. Beautifully renovated, designer decorated and newly furnished.';
  $property_type->field_sp_description['en'][0]['format'] = 'filtered_text';

  // Property Short Description.
  $property_type->field_sp_short_description['en'][0]['value'] = 'For lovers of the sea Casa Sul Mare is Eden.';

  // Search/Featured Image.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_0.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_featured_image[LANGUAGE_NONE][0] = (array) $default_image;

  // Image Gallery.
  for ($i = 0; $i <= 2; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_' . $i . '.jpg');
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Sea view deck',
      'alt' => 'Enjoy the wonderful views from our beautiful deck'
    );
    $default_image = file_copy($default_image, 'public://');
    $property_type->field_sp_gallery[LANGUAGE_NONE][$i] = (array) $default_image;
  }

  // Policies.
  $property_type->field_sp_policies['en'][0]['value'] = 'This is where you can define policies regarding the use of the accommodation such as pets, kids, check-in, check-out times, etc.';

  // Highlight Title.
  $property_type->field_sp_highlight_title['en'][0]['value'] = 'Casa Sul Mare';

  // Highlight Intro.
  $property_type->field_sp_highlight_intro['en'][0]['value'] = 'A wonderful house by the sea, Casa Sul Mare will be the home you will never want to leave. Relax out on the deck watching the waves and just walk down to the beack.';

  // Highlight Image 1.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_1.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image1[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 1 Caption.
  $property_type->field_sp_highlight_image1_cap['en'][0]['value'] = 'A wonderful living space always with sea views.';

  // Highlight Image 2.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_2.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image2[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 2 Caption.
  $property_type->field_sp_highlight_image2_cap['en'][0]['value'] = 'Even the bedroom offers beautiful views of the sea.';

  // Highlight Image 3.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_3.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image3[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 3 Caption.
  $property_type->field_sp_highlight_image3_cap['en'][0]['value'] = 'Enjoy dinner at night watching the waves hit the beach.';

  $property_type->field_sp_owner[LANGUAGE_NONE][0]['target_id'] = 1;

  $property_type->property_bat_type_reference[LANGUAGE_NONE][0]['target_id'] = $bat_type->type_id;

  $property_type->property_single_day_activity[LANGUAGE_NONE][0]['type_id'] = $bat_type->type_id;

  $property_type->save();
}

/**
 * Multi day Activity.
 */
function roomify_activity_example_content_create_multi_day_activity($images_folder) {
  $module_path = drupal_get_path('module', 'roomify_activity_example_content');

  $bat_type = bat_type_create(array(
    'type' => 'multi_day_activity',
    'name' => 'Cooking lesson',
    'status' => 1,
    'bookable' => 1,
    'created' => REQUEST_TIME,
    'uid' => 1,
  ));

  $bat_type->activity_duration[LANGUAGE_NONE][0]['value'] = 2;
  $bat_type->activity_default_price[LANGUAGE_NONE][0] = array(
    'amount' => 15000,
    'currency_code' => 'USD',
  );

  $bat_type->save();

  for ($i = 1; $i <= 4; $i++) {
    $unit = bat_unit_create(array('type' => 'default'));
    $unit->name = $bat_type->name . ' ' . $i;
    $unit->created = REQUEST_TIME;

    $unit->type_id = $bat_type->type_id;
    $unit->default_state = 1;
    $unit->uid = $bat_type->uid;
    $unit->save();
  }

  $property_type = roomify_property_create(array(
    'type' => 'multi_day_activity_property',
    'name' => 'Cooking lesson',
    'created' => REQUEST_TIME,
    'uid' => 1,
  ));

  // Property Description.
  $property_type->field_sp_description['en'][0]['value'] = 'This oceanfront home has an incredible view from its picture window. No streets to cross, just down the elevator to the beach. Beautifully renovated, designer decorated and newly furnished.';
  $property_type->field_sp_description['en'][0]['format'] = 'filtered_text';

  // Property Short Description.
  $property_type->field_sp_short_description['en'][0]['value'] = 'For lovers of the sea Casa Sul Mare is Eden.';

  // Search/Featured Image.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_0.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_featured_image[LANGUAGE_NONE][0] = (array) $default_image;

  // Image Gallery.
  for ($i = 0; $i <= 2; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_' . $i . '.jpg');
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Sea view deck',
      'alt' => 'Enjoy the wonderful views from our beautiful deck'
    );
    $default_image = file_copy($default_image, 'public://');
    $property_type->field_sp_gallery[LANGUAGE_NONE][$i] = (array) $default_image;
  }

  // Policies.
  $property_type->field_sp_policies['en'][0]['value'] = 'This is where you can define policies regarding the use of the accommodation such as pets, kids, check-in, check-out times, etc.';

  // Highlight Title.
  $property_type->field_sp_highlight_title['en'][0]['value'] = 'Casa Sul Mare';

  // Highlight Intro.
  $property_type->field_sp_highlight_intro['en'][0]['value'] = 'A wonderful house by the sea, Casa Sul Mare will be the home you will never want to leave. Relax out on the deck watching the waves and just walk down to the beack.';

  // Highlight Image 1.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_1.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image1[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 1 Caption.
  $property_type->field_sp_highlight_image1_cap['en'][0]['value'] = 'A wonderful living space always with sea views.';

  // Highlight Image 2.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_2.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image2[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 2 Caption.
  $property_type->field_sp_highlight_image2_cap['en'][0]['value'] = 'Even the bedroom offers beautiful views of the sea.';

  // Highlight Image 3.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_3.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image3[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 3 Caption.
  $property_type->field_sp_highlight_image3_cap['en'][0]['value'] = 'Enjoy dinner at night watching the waves hit the beach.';

  $property_type->field_sp_owner[LANGUAGE_NONE][0]['target_id'] = 1;

  $property_type->property_bat_type_reference[LANGUAGE_NONE][0]['target_id'] = $bat_type->type_id;

  $property_type->property_multi_day_activity[LANGUAGE_NONE][0]['type_id'] = $bat_type->type_id;

  $property_type->save();
}

/**
 * Single day Tour.
 */
function roomify_activity_example_content_create_single_day_tour($images_folder) {
  $module_path = drupal_get_path('module', 'roomify_activity_example_content');

  $bat_type = bat_type_create(array(
    'type' => 'single_day_tour',
    'name' => 'Tour of Colosseo',
    'status' => 1,
    'bookable' => 1,
    'created' => REQUEST_TIME,
    'uid' => 1,
  ));

  $bat_type->tours_max_capacity[LANGUAGE_NONE][0]['value'] = 10;
  $bat_type->tours_pricing_type[LANGUAGE_NONE][0]['value'] = 'Per person';
  $bat_type->tours_default_price[LANGUAGE_NONE][0] = array(
    'amount' => 25000,
    'currency_code' => 'USD',
  );

  $bat_type->save();

  $property_type = roomify_property_create(array(
    'type' => 'single_day_tour_property',
    'name' => 'Tour of Colosseo',
    'created' => REQUEST_TIME,
    'uid' => 1,
  ));

  // Property Description.
  $property_type->field_sp_description['en'][0]['value'] = 'This oceanfront home has an incredible view from its picture window. No streets to cross, just down the elevator to the beach. Beautifully renovated, designer decorated and newly furnished.';
  $property_type->field_sp_description['en'][0]['format'] = 'filtered_text';

  // Property Short Description.
  $property_type->field_sp_short_description['en'][0]['value'] = 'For lovers of the sea Casa Sul Mare is Eden.';

  // Search/Featured Image.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_0.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_featured_image[LANGUAGE_NONE][0] = (array) $default_image;

  // Image Gallery.
  for ($i = 0; $i <= 2; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_' . $i . '.jpg');
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Sea view deck',
      'alt' => 'Enjoy the wonderful views from our beautiful deck'
    );
    $default_image = file_copy($default_image, 'public://');
    $property_type->field_sp_gallery[LANGUAGE_NONE][$i] = (array) $default_image;
  }

  // Policies.
  $property_type->field_sp_policies['en'][0]['value'] = 'This is where you can define policies regarding the use of the accommodation such as pets, kids, check-in, check-out times, etc.';

  // Highlight Title.
  $property_type->field_sp_highlight_title['en'][0]['value'] = 'Casa Sul Mare';

  // Highlight Intro.
  $property_type->field_sp_highlight_intro['en'][0]['value'] = 'A wonderful house by the sea, Casa Sul Mare will be the home you will never want to leave. Relax out on the deck watching the waves and just walk down to the beack.';

  // Highlight Image 1.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_1.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image1[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 1 Caption.
  $property_type->field_sp_highlight_image1_cap['en'][0]['value'] = 'A wonderful living space always with sea views.';

  // Highlight Image 2.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_2.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image2[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 2 Caption.
  $property_type->field_sp_highlight_image2_cap['en'][0]['value'] = 'Even the bedroom offers beautiful views of the sea.';

  // Highlight Image 3.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_3.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image3[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 3 Caption.
  $property_type->field_sp_highlight_image3_cap['en'][0]['value'] = 'Enjoy dinner at night watching the waves hit the beach.';

  $property_type->field_sp_owner[LANGUAGE_NONE][0]['target_id'] = 1;

  $property_type->property_bat_type_reference[LANGUAGE_NONE][0]['target_id'] = $bat_type->type_id;

  $property_type->property_single_day_tour[LANGUAGE_NONE][0]['type_id'] = $bat_type->type_id;

  $property_type->save();
}

/**
 * Multi day Tour.
 */
function roomify_activity_example_content_create_multi_day_tour($images_folder) {
  $module_path = drupal_get_path('module', 'roomify_activity_example_content');

  $bat_type = bat_type_create(array(
    'type' => 'multi_day_tour',
    'name' => 'Italy tour',
    'status' => 1,
    'bookable' => 1,
    'created' => REQUEST_TIME,
    'uid' => 1,
  ));

  $bat_type->tours_max_capacity[LANGUAGE_NONE][0]['value'] = 10;
  $bat_type->tours_pricing_type[LANGUAGE_NONE][0]['value'] = 'Per person';
  $bat_type->tours_default_price[LANGUAGE_NONE][0] = array(
    'amount' => 25000,
    'currency_code' => 'USD',
  );

  $bat_type->save();

  $property_type = roomify_property_create(array(
    'type' => 'multi_day_tour_property',
    'name' => 'Italy tour',
    'created' => REQUEST_TIME,
    'uid' => 1,
  ));

  // Property Description.
  $property_type->field_sp_description['en'][0]['value'] = 'This oceanfront home has an incredible view from its picture window. No streets to cross, just down the elevator to the beach. Beautifully renovated, designer decorated and newly furnished.';
  $property_type->field_sp_description['en'][0]['format'] = 'filtered_text';

  // Property Short Description.
  $property_type->field_sp_short_description['en'][0]['value'] = 'For lovers of the sea Casa Sul Mare is Eden.';

  // Search/Featured Image.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_0.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_featured_image[LANGUAGE_NONE][0] = (array) $default_image;

  // Image Gallery.
  for ($i = 0; $i <= 2; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_' . $i . '.jpg');
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Sea view deck',
      'alt' => 'Enjoy the wonderful views from our beautiful deck'
    );
    $default_image = file_copy($default_image, 'public://');
    $property_type->field_sp_gallery[LANGUAGE_NONE][$i] = (array) $default_image;
  }

  // Policies.
  $property_type->field_sp_policies['en'][0]['value'] = 'This is where you can define policies regarding the use of the accommodation such as pets, kids, check-in, check-out times, etc.';

  // Highlight Title.
  $property_type->field_sp_highlight_title['en'][0]['value'] = 'Casa Sul Mare';

  // Highlight Intro.
  $property_type->field_sp_highlight_intro['en'][0]['value'] = 'A wonderful house by the sea, Casa Sul Mare will be the home you will never want to leave. Relax out on the deck watching the waves and just walk down to the beack.';

  // Highlight Image 1.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_1.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image1[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 1 Caption.
  $property_type->field_sp_highlight_image1_cap['en'][0]['value'] = 'A wonderful living space always with sea views.';

  // Highlight Image 2.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_2.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image2[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 2 Caption.
  $property_type->field_sp_highlight_image2_cap['en'][0]['value'] = 'Even the bedroom offers beautiful views of the sea.';

  // Highlight Image 3.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_3.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, 'public://');
  $property_type->field_sp_highlight_image3[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 3 Caption.
  $property_type->field_sp_highlight_image3_cap['en'][0]['value'] = 'Enjoy dinner at night watching the waves hit the beach.';

  $property_type->field_sp_owner[LANGUAGE_NONE][0]['target_id'] = 1;

  $property_type->property_bat_type_reference[LANGUAGE_NONE][0]['target_id'] = $bat_type->type_id;

  $property_type->property_multi_day_tour[LANGUAGE_NONE][0]['type_id'] = $bat_type->type_id;

  $property_type->save();
}
