<?php

/**
 * @file
 * Install, update and uninstall functions for the Roomify Activity Example Content module.
 */

/**
 * Implements hook_install().
 */
function roomify_activity_example_content_install() {
  roomify_activity_example_content_create_single_day_activity('single_day_activity');
  roomify_activity_example_content_create_multi_day_activity('multi_day_activity');
  roomify_activity_example_content_create_single_day_tour('single_day_tour');
  roomify_activity_example_content_create_multi_day_tour('multi_day_tour');
}
