<?php

/**
 * @file
 */

/**
 * Implements hook_default_cer().
 */
function roomify_locanda_default_cer() {
  $items = array();

  $items['roomify_property:locanda_property:property_bat_type_reference*bat_type:room:field_st_property_reference'] = entity_import('cer', '{
    "identifier" : "roomify_property:locanda_property:property_bat_type_reference*bat_type:room:field_st_property_reference",
    "cer_bidirectional" : { "und" : [ { "value" : "1" } ] },
    "cer_enabled" : { "und" : [ { "value" : "1" } ] },
    "cer_weight" : { "und" : [ { "value" : "0" } ] },
    "cer_left" : { "und" : [
        { "path" : "roomify_property:locanda_property:property_bat_type_reference" }
      ]
    },
    "cer_right" : { "und" : [ { "path" : "bat_type:room:field_st_property_reference" } ] },
    "rdf_mapping" : []
  }');

  return $items;
}
