<?php

/**
 * @file
 * Code for the Roomify Search feature.
 */

include_once 'roomify_search.features.inc';

/**
 * Implements hook_page_alter().
 */
function roomify_search_page_alter(&$page) {
  if (strpos(current_path(), 'availability-search') !== FALSE) {
    // Kill breadcrumb, set to empty array.
    drupal_set_breadcrumb(array());
  }
}

/**
 * Implements hook_views_handlers().
 */
function roomify_search_views_handlers() {
  return array(
    'info' => array(
      'path' => drupal_get_path('roomify_search', 'views'),
    ),
    'handlers' => array(
      // The name of my handler.
      'roomify_search_handler_type_property_types' => array(
        // The name of the handler we are extending.
        'parent' => 'views_handler_field',
      ),
    ),
  );
}

/**
 * Implements hook_metatag_metatags_view_alter()
 */
function roomify_search_metatag_metatags_view_alter(&$output, $instance) {
  // Add Canonical for the general /availability-search page.
  if (strpos($_GET['q'], 'availability-search') === 0) {
    global $base_url;
    $output['canonical']['#attached']['drupal_add_html_head'][0][0]['#value'] = $base_url . '/availability-search';
  }
}
