<?php

/**
 * @file
 * Code for the Roomify Homepage module.
 */

/**
 * Implements hook_image_default_styles().
 */
function roomify_homepage_image_default_styles() {
  $styles = array();

  // Exported image style: 1600x580.
  $styles['1600x580'] = array(
    'label' => '1600x580',
    'effects' => array(
      1 => array(
        'name' => 'manualcrop_crop_and_scale',
        'data' => array(
          'width' => 1600,
          'height' => 580,
          'upscale' => 1,
          'respectminimum' => 1,
          'onlyscaleifcrop' => 0,
          'style_name' => '1600x580',
        ),
        'weight' => 0,
      ),
    ),
  );

  return $styles;
}

/**
 * Implements hook_ctools_plugin_api().
 */
function roomify_homepage_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function roomify_homepage_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'roomify_homepage') . '/views',
  );
}

/**
 * Implements hook_node_info().
 */
function roomify_homepage_node_info() {
  $items = array(
    'homepage' => array(
      'name' => t('Homepage'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}

/**
 * Implements hook_form_alter().
 */
function roomify_homepage_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'homepage_node_form') {
    if (isset($form['field_homepage_style'][LANGUAGE_NONE]['#options']['_none'])) {
      unset($form['field_homepage_style'][LANGUAGE_NONE]['#options']['_none']);
    }
    if (isset($form['field_homepage_areas_style'][LANGUAGE_NONE]['#options']['_none'])) {
      unset($form['field_homepage_areas_style'][LANGUAGE_NONE]['#options']['_none']);
    }
    if (isset($form['field_homepage_properties_style'][LANGUAGE_NONE]['#options']['_none'])) {
      unset($form['field_homepage_properties_style'][LANGUAGE_NONE]['#options']['_none']);
    }
  }
}

/**
 * Implements hook_views_pre_render().
 */
function roomify_homepage_views_pre_render(&$view) {
  if ($view->name == 'homepage') {
    if ($view->current_display == 'panel_pane_2') {
      $items = count($view->result);
      $view->display_handler->set_option('css_class', $items . '-items homepage-properties-lists');
    }
  }
}
