<?php

/**
 * @file
 * Code for the Roomify Homepage module.
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function roomify_homepage_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_views_api().
 */
function roomify_homepage_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'roomify_homepage') . '/views',
  );
}

/**
 * Implements hook_node_info().
 */
function roomify_homepage_node_info() {
  $items = array(
    'homepage' => array(
      'name' => t('Homepage'),
      'base' => 'node_content',
      'description' => '',
      'has_title' => '1',
      'title_label' => t('Title'),
      'help' => '',
    ),
  );
  drupal_alter('node_info', $items);
  return $items;
}
