<?php

/**
 * @file
 * Code for the Roomify Properties List feature.
 */

include_once 'roomify_properties_list.features.inc';

/**
 * Implements hook_search_api_db_query_alter().
 *
 * @param SelectQueryInterface $db_query
 *   The database query to be executed for the search. Will have "item_id" and
 *   "score" columns in its result.
 * @param SearchApiQueryInterface $query
 *   The search query that is being executed.
 */
function roomify_properties_list_search_api_db_query_alter(SelectQueryInterface &$db_query, SearchApiQueryInterface $query) {
  if ($node = menu_get_object()) {
    if ($node->type == 'properties_list') {
      $info = entity_get_info($query->getIndex()->getEntityType());

      if ($info['base table'] == 'roomify_properties') {
        $properties_ids = array();

        if (isset($node->field_properties_list_properties[LANGUAGE_NONE])) {
          foreach ($node->field_properties_list_properties[LANGUAGE_NONE] as $property) {
            $properties_ids[] = $property['target_id'];
          }
        }

        $db_query->condition($info['entity keys']['id'], $properties_ids, 'IN');

        if ($properties_ids) {
          $db_query->orderBy('FIELD(' . $info['entity keys']['id'] . ',' . implode(',', $properties_ids) . ')');
        }
      }
    }
  }
}

/**
 * Implements hook_metatag_metatags_view_alter()
 */
function roomify_properties_list_metatag_metatags_view_alter(&$output, $instance) {
  // Add Custom logic to overwrite the canonical tag here.
  if ($node = menu_get_object()) {
    if ($node->type == 'properties_list') {
      global $base_url;
      $alias = drupal_get_path_alias('node/' . $node->nid);
      $output['canonical']['#attached']['drupal_add_html_head'][0][0]['#value'] = $base_url . '/' . $alias;
    }
  }
}
