<?php

/**
 * @file
 * Install and update hooks for roomify_payment_methods module.
 */

/**
 * Implements hook_install().
 */
function roomify_payment_methods_install() {
  // Create custom Payment record.
  $record = array(
    'id' => 'custom',
    'title' => 'Custom',
    'description' => '',
    'information' => '',
    'format' => 'filtered_text',
  );

  commerce_cop_payment_save($record);
}
