<?php

/**
 * @file
 * Code for the Roomify Integrations module.
 */

/**
 * Implements hook_menu().
 */
function roomify_integrations_menu() {
  $items = array();

  $items['admin/config/roomify-integrations'] = array(
    'title' => 'Enable Roomify Integrations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('roomify_integrations_form'),
    'access arguments' => array('administer roomify integrations'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/roomify-integrations/enable'] = array(
    'title' => 'Enable Roomify Integrations',
    'access arguments' => array('administer roomify integrations'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/roomify-integrations/manage'] = array(
    'title' => 'Manage Roomify Integrations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('roomify_manage_integrations_form'),
    'access arguments' => array('administer roomify integrations'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function roomify_integrations_permission() {
  return array(
    'administer roomify integrations' => array(
      'title' => t('Administer Roomify Integrations'),
      'description' => t('Administer Roomify Integrations'),
    ),
  );
}

/**
 * Implements hook_roomify_rights().
 */
function roomify_integrations_roomify_rights() {
  $rights['roomify_integrations'] = array(
    'roomify manager' => array(
      'administer roomify integrations',
    ),
  );
  if (module_exists('zopim')) {
    $rights['roomify_integrations']['roomify manager'][] = 'administer zopim';
  }
  if (module_exists('googleanalytics')) {
    $rights['roomify_integrations']['roomify manager'][] = 'administer google analytics';
  }

  return $rights;
}

/**
 * Form Enable "Roomify Integrations".
 */
function roomify_integrations_form($form, &$form_state) {
  $module_path = drupal_get_path('module', 'roomify_integrations');
  $form['#attached']['css'] = array($module_path . '/css/roomify_integrations.css');
  $form['roomify_integration_intro'] = array(
    '#markup' => '<h2>' . t("Here you can find a list of integrations to enable.") . '</h2>',
  );

  $integrations = db_select('roomify_integrations', 'i')
    ->fields('i')
    ->execute()
    ->fetchAll();

  foreach ($integrations as $integration) {
    $form['roomify_integration'][$integration->name] = array(
      '#type' => 'checkbox',
      '#title' => t('Enable @integration Integration', array('@integration' => $integration->label)),
      '#default_value' => $integration->status,
    );
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Save Configuration'),
  );

  return $form;
}

/**
 * Enable or disable integrations.
 */
function roomify_integrations_form_submit(&$form, &$form_state) {
  $values = $form_state['values'];
  // Zopim Integration.
  if (isset($values['zopim'])) {
    if ($values['zopim'] == 1) {
      $zopim_status = 1;
      if (!module_exists('zopim')) {
        module_enable(array('zopim'));
      }
    }
    else {
      $zopim_status = 0;
      if (module_exists('zopim')) {
        module_disable(array('zopim'));
      }
    }
    $record = array(
      'name' => 'zopim',
      'label' => 'Zopim',
      'status' => $zopim_status,
    );

    drupal_write_record('roomify_integrations', $record, array('name'));
    menu_rebuild();
  }

  // Google Analytics Integration.
  if (isset($values['googleanalytics'])) {
    if ($values['googleanalytics'] == 1) {
      $googleanalytics_status = 1;
      if (!module_exists('googleanalytics')) {
        module_enable(array('googleanalytics'));
      }
    }
    else {
      $googleanalytics_status = 0;
      if (module_exists('googleanalytics')) {
        module_disable(array('googleanalytics'));
      }
    }
    $record = array(
      'name' => 'googleanalytics',
      'label' => 'Google Analytics',
      'status' => $googleanalytics_status,
    );

    drupal_write_record('roomify_integrations', $record, array('name'));
    menu_rebuild();
  }
  drupal_flush_all_caches();
}

/**
 * Form "Manage Roomify Integrations".
 */
function roomify_manage_integrations_form($form, &$form_state) {
  $module_path = drupal_get_path('module', 'roomify_integrations');

  $form['message'] = array(
    '#markup' => '<div class="message"><h2>' . t('Manage Roomify Integrations') . '</h2></div>',
  );
  $form['#attached']['css'] = array($module_path . '/css/roomify_integrations.css');

  $integrations = db_select('roomify_integrations', 'i')
    ->fields('i')
    ->condition('status', 1, '=')
    ->execute()
    ->fetchAll();

  foreach ($integrations as $integration) {
    if ($integration->name == 'zopim') {
      $zopim_path = '/admin/config/system/zopim';
      $zopim_image = theme_image(array('path' => $module_path . '/images/zopim.png', 'attributes' => ''));

      $form['zopim'] = array(
        '#markup' => '<div class="zopim-integration">' . l($zopim_image . '<h3>' . t('Zopim Chat') . '</h3>' . t('Talk to your customers in real-time using a live chat.'), $zopim_path, array('html' => TRUE)) . '</div>'
      );
    }

    if ($integration->name == 'googleanalytics') {
      $googleanalytics_path = '/admin/config/system/googleanalytics';
      $googleanalytics_image = theme_image(array('path' => $module_path . '/images/googleanalytics.png', 'attributes' => ''));

      $form['googleanalytics'] = array(
        '#markup' => '<div class="googleanalytics-integration">' . l($googleanalytics_image . '<h3>' . t('Google Analytics') . '</h3>' . t('Manage Google Analytics settings.'), $googleanalytics_path, array('html' => TRUE)) . '</div>'
      );
    }
  }

  return $form;
}
