<?php

/**
 * @file
 * Code for the Roomify Integrations module.
 */

/**
 * Implements hook_menu().
 */
function roomify_integrations_menu() {
  $items = array();

  $items['admin/config/roomify-integrations'] = array(
    'title' => 'Enable Roomify Integrations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('roomify_integrations_form'),
    'access arguments' => array('administer roomify integrations'),
    'type' => MENU_CALLBACK,
  );
  $items['admin/config/roomify-integrations/enable'] = array(
    'title' => 'Enable Roomify Integrations',
    'access arguments' => array('administer roomify integrations'),
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );
  $items['admin/config/roomify-integrations/manage'] = array(
    'title' => 'Manage Roomify Integrations',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('roomify_manage_integrations_form'),
    'access arguments' => array('administer roomify integrations'),
    'type' => MENU_LOCAL_TASK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function roomify_integrations_permission() {
  return array(
    'administer roomify integrations' => array(
      'title' => t('Administer Roomify Integrations'),
      'description' => t('Administer Roomify Integrations'),
    ),
  );
}

/**
 * Implements hook_roomify_rights().
 */
function roomify_integrations_roomify_rights() {
  $rights['roomify_integrations'] = array(
    'roomify manager' => array(
      'administer roomify integrations',
      'administer zopim',
    ),
  );

  return $rights;
}

/**
 * Form Enable "Roomify Integrations".
 */
function roomify_integrations_form($form, &$form_state) {
  $module_path = drupal_get_path('module', 'roomify_integrations');
  $form['#attached']['css'] = array($module_path . '/css/roomify_integrations.css');
  $form['roomify_integration_intro'] = array(
    '#markup' => '<h2>' . t("Here you can find a list of Integration to enable.") . '</h2>',
  );

  $form['roomify_integration_zopim'] = array(
    '#type' => 'checkbox',
    '#title' => t('Enable Zopim Integration'),
    '#default_value' => variable_get('roomify_integration_zopim', 0),
  );

  $form['#submit'][] = 'roomify_integrations_form_submit';
  return system_settings_form($form);
}

/**
 * Enable or disable integrations.
 */
function roomify_integrations_form_submit(&$form, &$form_state) {
  $values = $form_state['values'];

  if (isset($values['roomify_integration_zopim'])) {
    if ($values['roomify_integration_zopim'] == 1) {
      if (!module_exists('zopim')) {
        module_enable(array('zopim'));
      }
    }
    else {
      if (module_exists('zopim')) {
        module_disable(array('zopim'));
      }
    }
    menu_rebuild();
  }
}

/**
 * Form "Manage Roomify Integrations".
 */
function roomify_manage_integrations_form($form, &$form_state) {
  $module_path = drupal_get_path('module', 'roomify_integrations');

  $form['message'] = array(
    '#markup' => '<div class="message"><h2>' . t('Manage Roomify Integrations') . '</h2></div>',
  );
  $form['#attached']['css'] = array($module_path . '/css/roomify_integrations.css');

  if (variable_get('roomify_integration_zopim', 0) == 1) {
    $zopim_path = '/admin/config/system/zopim';
    $zopim_image = theme_image(array('path' => $module_path . '/images/zopim.png', 'attributes' => ''));

    $form['zopim'] = array(
      '#markup' => '<div class="zopim-integration">' . l($zopim_image . '<h3>' . t('Zopim Chat') . '</h3>' . t('Talk to your customers in real-time using a live chat.'), $zopim_path, array('html' => TRUE)) . '</div>'
    );
  }

  return $form;
}
