<?php

/**
 * @file
 * Code for the Roomify Things to do feature.
 */

include_once 'roomify_things_to_do.features.inc';

/**
 * Implements hook_theme_registry_alter().
 */
function roomify_things_to_do_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'roomify_things_to_do');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}

/**
 * Implements hook_roomify_rights().
 */
function roomify_things_to_do_roomify_rights() {
  $rights['roomify_things_to_do'] = array(
    'activity manager' => array(),
    'roomify manager' => array(
      'add terms in activity',
      'edit terms in activity',
      'delete terms in activity',
    ),
  );

  return $rights;
}
