<?php

/**
 * @file
 * Provides functionality and configuration for the Roomify Accommodation example content module.
 */

use Roomify\Bat\Calendar\Calendar;
use Roomify\Bat\Event\Event;
use Roomify\Bat\Store\DrupalDBStore;
use Roomify\Bat\Unit\Unit;
use Roomify\Bat\Valuator\IntervalValuator;

/**
 * Implements hook_menu().
 */
function roomify_accommodation_example_content_menu() {
  $items = array();

  $items['admin/bat/config/example-content'] = array(
    'title' => 'Quick Setup',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('roomify_accommodation_example_content_manage_form'),
    'access arguments' => array('administer roomify global site settings'),
  );

  $items['admin/bat/config/example-content/delete'] = array(
    'title' => 'Remove example content',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('roomify_accommodation_example_content_delete_form'),
    'access arguments' => array('administer roomify global site settings'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function roomify_accommodation_example_content_permission() {
  return array(
    'administer roomify quick setup' => array(
      'title' => t('Administer Roomify Quick Setup'),
      'description' => t('Configure a Roomify Site.'),
    ),
  );
}

/**
 * Implements hook_roomify_rights().
 */
function roomify_accommodation_example_content_roomify_rights() {

  $rights['roomify_system'] = array(
    'roomify manager' => array(
      'administer roomify quick setup',
    ),
  );

  return $rights;
}

/**
 * Create an example location node.
 */
function roomify_example_content_create_location_example_node() {
  $location = new stdClass();
  $location->type = 'location';
  $location->title = 'My Property';
  $location->language = LANGUAGE_NONE;
  $location->field_accommodation[LANGUAGE_NONE][0]['value'] = '1';
  $location->field_address[LANGUAGE_NONE][0]['country'] = 'IT';
  $location->field_address[LANGUAGE_NONE][0]['administrative_area'] = 'PA';
  $location->field_address[LANGUAGE_NONE][0]['locality'] = 'Cefalù';
  $location->field_address[LANGUAGE_NONE][0]['postal_code'] = '90015';
  $location->field_address[LANGUAGE_NONE][0]['thoroughfare'] = 'Lungomare Giuseppe Giardina 21';
  $location->field_map_coordinates[LANGUAGE_NONE][0]['lat'] = '38.03656625437375';
  $location->field_map_coordinates[LANGUAGE_NONE][0]['lon'] = '14.018212568717217';

  node_save($location);
}

/**
 * Enable the Roomify Homepage module.
 */
function roomify_example_content_create_homepage_node($pid1, $pid2, $pid3) {
  module_enable(array('roomify_homepage'));
  drupal_flush_all_caches();

  // Add some featured properties.
  $queue = entityqueue_queue_load('featured_properties');
  $subqueue = entityqueue_subqueue_load(reset($queue));
  $subqueue->eq_roomify_property[LANGUAGE_NONE] = array(
    0 => array('target_id' => $pid1),
    1 => array('target_id' => $pid2),
    2 => array('target_id' => $pid3),
  );
  $subqueue->save();

  // Add some featured areas.
  $queue = entityqueue_queue_load('featured_areas');
  $subqueue = entityqueue_subqueue_load(reset($queue));

  foreach (variable_get('roomify_accommodation_example_content_location_tids', array()) as $id => $tid) {
    $subqueue->eq_taxonomy_term[LANGUAGE_NONE][$id]['target_id'] = $tid;
  }
  $subqueue->save();
}

/**
 * Create a property list node.
 */
function roomify_example_content_create_properties_list_node($p1, $p2, $p3) {
  $example_nodes = array('pool' => array('title' => 'Villas with pool'), 'mountain' => array('title' => 'Lost in the mountains'), 'beach' => array('title' => 'In the beach!'));

  foreach ($example_nodes as $key => $value) {
    $node = new stdClass();
    $node->type = 'properties_list';
    $node->title = $value['title'];
    $node->language = 'en';
    $node->uid = 1;
    $node->status = 1;
    $node->path['pathauto'] = 1;
    $node = node_submit($node);

    $image = file_get_contents(drupal_get_path('module', 'roomify_accommodation_example_content') . '/default_images/' . $key . '/featured.jpg');
    $image = file_save_data($image, roomify_system_file_dir() . $key . '.jpg', FILE_EXISTS_RENAME);

    $node->body['en'][0]['value'] = '<p style="text-align: justify;">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.&nbsp;Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>';
    $node->body['en'][0]['format'] = 'filtered_text';
    $node->field_pl_featured_image[LANGUAGE_NONE][0] = array(
      'fid' => $image->fid,
      'filename' => $image->filename,
      'filemime' => $image->filemime,
      'uid' => 1,
      'uri' => $image->uri,
      'status' => 1,
      'display' => 1,
    );
    $node->title_field['en'][0]['value'] = $value['title'];

    $node->field_properties_list_properties[LANGUAGE_NONE][0]['target_id'] = $p1;
    $node->field_properties_list_properties[LANGUAGE_NONE][1]['target_id'] = $p2;
    $node->field_properties_list_properties[LANGUAGE_NONE][2]['target_id'] = $p3;

    $highlight1 = file_get_contents(drupal_get_path('module', 'roomify_accommodation_example_content') . '/default_images/' . $key . '/highlight1.jpg');
    $highlight1 = file_save_data($highlight1, roomify_system_file_dir() . 'highlight1.jpg', FILE_EXISTS_RENAME);

    $highlight2 = file_get_contents(drupal_get_path('module', 'roomify_accommodation_example_content') . '/default_images/' . $key . '/highlight2.jpg');
    $highlight2 = file_save_data($highlight2, roomify_system_file_dir() . 'highlight2.jpg', FILE_EXISTS_RENAME);

    $highlight3 = file_get_contents(drupal_get_path('module', 'roomify_accommodation_example_content') . '/default_images/' . $key . '/highlight3.jpg');
    $highlight3 = file_save_data($highlight3, roomify_system_file_dir() . 'highlight3.jpg', FILE_EXISTS_RENAME);

    $node->field_sp_highlight_image1[LANGUAGE_NONE][0] = array(
      'fid' => $highlight1->fid,
      'filename' => $highlight1->filename,
      'filemime' => $highlight1->filemime,
      'uid' => 1,
      'uri' => $highlight1->uri,
      'status' => 1,
      'display' => 1,
    );
    // Highlight Image 3 Caption.
    $node->field_sp_highlight_image1_cap['en'][0]['value'] = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.';
    $node->field_sp_highlight_image2[LANGUAGE_NONE][0] = array(
      'fid' => $highlight2->fid,
      'filename' => $highlight2->filename,
      'filemime' => $highlight2->filemime,
      'uid' => 1,
      'uri' => $highlight2->uri,
      'status' => 1,
      'display' => 1,
    );
    $node->field_sp_highlight_image2_cap['en'][0]['value'] = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.';
    $node->field_sp_highlight_image3[LANGUAGE_NONE][0] = array(
      'fid' => $highlight3->fid,
      'filename' => $highlight3->filename,
      'filemime' => $highlight3->filemime,
      'uid' => 1,
      'uri' => $highlight3->uri,
      'status' => 1,
      'display' => 1,
    );
    $node->field_sp_highlight_image3_cap['en'][0]['value'] = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.';
    node_save($node);
  }
}

/**
 * Create a type "Example Casa".
 */
function roomify_example_content_create_casa_example_type($name, $capacity, $images_folder, $uid, $price = '1000') {
  $module_path = drupal_get_path('module', 'roomify_accommodation_example_content');

  $bat_type = bat_type_create(array(
    'type' => 'home',
    'name' => $name,
    'status' => 1,
    'bookable' => 1,
    'created' => REQUEST_TIME,
    'uid' => $uid,
  ));

  // Bedrooms and Bathrooms.
  $bat_type->field_st_max_capacity[LANGUAGE_NONE][0]['value'] = $capacity;
  $bat_type->field_st_single_bed[LANGUAGE_NONE][0]['value'] = 2;
  $bat_type->field_st_double_bed[LANGUAGE_NONE][0]['value'] = 2;
  $bat_type->field_st_bedrooms[LANGUAGE_NONE][0]['value'] = 3;
  $bat_type->field_st_bathrooms[LANGUAGE_NONE][0]['value'] = 2;

  // Default Price.
  $bat_type->field_st_default_price[LANGUAGE_NONE][0] = array(
    'amount' => $price,
    'currency_code' => 'USD',
    'data' => array(
      'components' => array(),
    ),
  );

  // Description.
  $bat_type->field_st_description[LANGUAGE_NONE][0]['value'] = 'A description of your vacation rental and the story behind it. Use the very first phrase to capture peoples imagination with an interesting fact such as "This house dates back to the 17th century when it was the summer home of Lord Byron".';

  // Gallery.
  for ($i = 0; $i <= 3; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_' . $i . '.jpg');
    // Create managed File object and associate with Image field.
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Image title',
      'alt' => 'this is a description of the image.'
    );

    // Save the file to the root of the files directory.
    $default_image = file_copy($default_image, roomify_system_file_dir());
    $bat_type->field_st_gallery[LANGUAGE_NONE][$i] = (array) $default_image;
  }

  // Amenities.
  for ($i = 1; $i <= 14; $i++) {
    $bat_type->field_st_amenities[LANGUAGE_NONE][$i]['tid'] = $i;
  }

  // Save Type.
  bat_type_save($bat_type);

  // Create a unit for the casa type.
  $unit = bat_unit_create(array('type' => 'default'));
  $unit->name = $name . ' 1';
  $unit->created = !empty($unit->date) ? strtotime($unit->date) : REQUEST_TIME;

  $unit->type_id = $bat_type->type_id;
  $unit->default_state = 1;
  $unit->uid = $uid;
  $unit->save();

  return $bat_type->type_id;
}

/**
 * Create "Casa Sul Mare" property.
 */
function roomify_example_content_create_casa_sul_mare_example_property($type_id, $images_folder, $owner, $property_name = 'Casa Sul Mare') {
  $module_path = drupal_get_path('module', 'roomify_accommodation_example_content');

  $property_type = roomify_property_create(array(
    'type' => 'casa_property',
    'name' => $property_name,
    'created' => REQUEST_TIME,
    'language' => 'en',
  ));

  // Property Description.
  $property_type->field_sp_description['en'][0]['value'] = 'This oceanfront home has an incredible view from its picture window. No streets to cross, just down the elevator to the beach. Beautifully renovated, designer decorated and newly furnished.';
  $property_type->field_sp_description['en'][0]['format'] = 'filtered_text';

  // Property Short Description.
  $property_type->field_sp_short_description['en'][0]['value'] = 'For lovers of the sea Casa Sul Mare is Eden.';

  // Search/Featured Image.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_0.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_featured_image[LANGUAGE_NONE][0] = (array) $default_image;

  // Image Gallery.
  for ($i = 0; $i <= 2; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_' . $i . '.jpg');
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Sea view deck',
      'alt' => 'Enjoy the wonderful views from our beautiful deck'
    );
    $default_image = file_copy($default_image, roomify_system_file_dir());
    $property_type->field_sp_gallery['en'][$i] = (array) $default_image;
  }

  // Policies.
  $property_type->field_sp_policies['en'][0]['value'] = 'This is where you can define policies regarding the use of the accommodation such as pets, kids, check-in, check-out times, etc.';

  // Highlight Title.
  $property_type->field_sp_highlight_title['en'][0]['value'] = 'Casa Sul Mare';

  // Highlight Intro.
  $property_type->field_sp_highlight_intro['en'][0]['value'] = 'A wonderful house by the sea, Casa Sul Mare will be the home you will never want to leave. Relax out on the deck watching the waves and just walk down to the beack.';

  // Highlight Image 1.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_1.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image1[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 1 Caption.
  $property_type->field_sp_highlight_image1_cap['en'][0]['value'] = 'A wonderful living space always with sea views.';

  // Highlight Image 2.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_2.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image2[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 2 Caption.
  $property_type->field_sp_highlight_image2_cap['en'][0]['value'] = 'Even the bedroom offers beautiful views of the sea.';

  // Highlight Image 3.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_3.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image3[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 3 Caption.
  $property_type->field_sp_highlight_image3_cap['en'][0]['value'] = 'Enjoy dinner at night watching the waves hit the beach.';

  // Area.
  foreach (variable_get('roomify_accommodation_example_content_location_tids', array()) as $tid) {
    $property_type->field_sp_area[LANGUAGE_NONE][]['tid'] = $tid;
  }

  // Location.
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geom'] = 'POINT (12.7317810 38.1882757)';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geo_type'] = 'point';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['lat'] = '38.188275720600';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['lon'] = '12.731781005900';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['left'] = '12.731781005900';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['right'] = '12.731781005900';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['top'] = '38.188275720600';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['bottom'] = '38.188275720600';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geohash'] = 'sqc11xyyzfxczvzc';

  // How to reach the Place.
  $property_type->field_sp_how_to_reach['en'][0]['value'] = 'You can provide instructions here on how to reach the place.';

  // Essentials Nearby.
  $property_type->field_sp_essentials['en'][0]['value'] = 'What is nearby?  Supermarkets, pharmacies, restaurants, etc.';

  $property_type->property_bat_type_reference[LANGUAGE_NONE][0]['target_id'] = $type_id;

  $user = user_load_by_name($owner);
  $property_type->uid = $user->uid;
  $property_type->field_sp_owner[LANGUAGE_NONE][0]['target_id'] = $user->uid;

  $property_type->save();

  $type = bat_type_load($type_id);
  $type->field_st_property_reference[LANGUAGE_NONE][0]['target_id'] = $property_type->property_id;
  $type->save();

  return $property_type->property_id;
}

/**
 * Create "Casa Azzurra" property.
 */
function roomify_example_content_create_casa_azzurra_example_property($type_id, $images_folder, $owner) {
  $module_path = drupal_get_path('module', 'roomify_accommodation_example_content');

  $property_type = roomify_property_create(array(
    'type' => 'casa_property',
    'name' => 'Casa Azzurra',
    'created' => REQUEST_TIME,
    'language' => 'en',
  ));

  // Property Description.
  $property_type->field_sp_description['en'][0]['value'] = 'Did you know that the whole complex of Santorini islands is still an active volcano (the same as Méthana, Mílos and Nísiros) and probably the only volcano in the world whose crater is in the sea? The islands that form Santorini came into existence as a result of intensive volcanic activity; twelve huge eruptions occurred, one every 20,000 years approximately, and each violent eruption caused the collapse of the volcano’s central part creating a large crater (caldera). The volcano, however, managed to recreate itself over and over again.';
  $property_type->field_sp_description['en'][0]['format'] = 'filtered_text';

  // Property Short Description.
  $property_type->field_sp_short_description['en'][0]['value'] = 'Surrounded by the sea, bathed in sunlight.';

  // Search/Featured Image.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_0.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_featured_image[LANGUAGE_NONE][0] = (array) $default_image;

  // Image Gallery.
  for ($i = 0; $i <= 2; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_' . $i . '.jpg');
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Sea view deck',
      'alt' => 'Enjoy the wonderful views from our beautiful deck'
    );
    $default_image = file_copy($default_image, roomify_system_file_dir());
    $property_type->field_sp_gallery['en'][$i] = (array) $default_image;
  }

  // Policies.
  $property_type->field_sp_policies['en'][0]['value'] = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

  // Highlight Title.
  $property_type->field_sp_highlight_title['en'][0]['value'] = 'Casa Azzurra';

  // Highlight Intro.
  $property_type->field_sp_highlight_intro['en'][0]['value'] = 'An amazing location on the beautiful island of Santorini. Casa Azzurra offers access to all the best spots on the island.';

  // Highlight Image 1.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_1.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image1[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 1 Caption.
  $property_type->field_sp_highlight_image1_cap['en'][0]['value'] = 'Enjoy greek meals while taking in the sights.';

  // Highlight Image 2.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_2.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image2[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 2 Caption.
  $property_type->field_sp_highlight_image2_cap['en'][0]['value'] = 'Everywhere you look the sea reigns supreme.';

  // Highlight Image 3.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_3.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image3[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 3 Caption.
  $property_type->field_sp_highlight_image3_cap['en'][0]['value'] = 'A fully equipped indoors kitchen.';

  // Area.
  foreach (variable_get('roomify_accommodation_example_content_location_tids', array()) as $tid) {
    $property_type->field_sp_area[LANGUAGE_NONE][]['tid'] = $tid;
  }

  // Location.
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geom'] = 'POINT (15.2895355 37.8514078)';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geo_type'] = 'point';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['lat'] = '37.851407899700';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['lon'] = '15.289535522500';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['left'] = '15.289535522500';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['right'] = '15.289535522500';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['top'] = '37.851407899700';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['bottom'] = '37.851407899700';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geohash'] = 'sqdz7ftkrvzgpgru';

  // How to reach the Place.
  $property_type->field_sp_how_to_reach['en'][0]['value'] = 'You can provide instructions here on how to reach the place.';

  // Essentials Nearby.
  $property_type->field_sp_essentials['en'][0]['value'] = 'What is nearby?  Supermarkets, pharmacies, restaurants, etc.';

  $property_type->property_bat_type_reference[LANGUAGE_NONE][0]['target_id'] = $type_id;

  $user = user_load_by_name($owner);
  $property_type->uid = $user->uid;
  $property_type->field_sp_owner[LANGUAGE_NONE][0]['target_id'] = $user->uid;

  $property_type->save();

  $type = bat_type_load($type_id);
  $type->field_st_property_reference[LANGUAGE_NONE][0]['target_id'] = $property_type->property_id;
  $type->save();

  return $property_type->property_id;
}

/**
 * Create a type "Example Locanda".
 */
function roomify_example_content_create_example_types($name1, $capacity1, $images_folder1, $price1, $name2, $capacity2, $images_folder2, $price2, $uid) {
  $module_path = drupal_get_path('module', 'roomify_accommodation_example_content');

  // Standard type.
  $bat_type_1 = bat_type_create(array(
    'type' => 'room',
    'name' => $name1,
    'status' => 1,
    'bookable' => 1,
    'created' => REQUEST_TIME,
    'uid' => $uid,
  ));

  // Bedrooms and Bathrooms.
  $bat_type_1->field_st_max_capacity[LANGUAGE_NONE][0]['value'] = $capacity1;
  $bat_type_1->field_st_single_bed[LANGUAGE_NONE][0]['value'] = 2;
  $bat_type_1->field_st_double_bed[LANGUAGE_NONE][0]['value'] = 2;
  $bat_type_1->field_st_bedrooms[LANGUAGE_NONE][0]['value'] = 3;
  $bat_type_1->field_st_bathrooms[LANGUAGE_NONE][0]['value'] = 2;

  // Default Price.
  $bat_type_1->field_st_default_price[LANGUAGE_NONE][0] = array(
    'amount' => $price1,
    'currency_code' => 'USD',
    'data' => array(
      'components' => array(),
    ),
  );

  // Description.
  $bat_type_1->field_st_description[LANGUAGE_NONE][0]['value'] = 'A description of your vacation rental and the story behind it. Use the very first phrase to capture peoples imagination with an interesting fact such as "This house dates back to the 17th century when it was the summer home of Lord Byron".';

  // Gallery.
  for ($i = 0; $i <= 3; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder1 . '/default_' . $i . '.jpg');
    // Create managed File object and associate with Image field.
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Image title',
      'alt' => 'this is a description of the image.'
    );

    // Save the file to the root of the files directory.
    $default_image = file_copy($default_image, roomify_system_file_dir());
    $bat_type_1->field_st_gallery[LANGUAGE_NONE][$i] = (array) $default_image;
  }

  // Amenities.
  for ($i = 1; $i <= 14; $i++) {
    $bat_type_1->field_st_amenities[LANGUAGE_NONE][$i]['tid'] = $i;
  }

  // Save Type.
  bat_type_save($bat_type_1);

  // Create a unit.
  $unit = bat_unit_create(array('type' => 'default'));
  $unit->name = $name1 . ' 1';
  $unit->created = !empty($unit->date) ? strtotime($unit->date) : REQUEST_TIME;

  $unit->type_id = $bat_type_1->type_id;
  $unit->default_state = 1;
  $unit->uid = $uid;
  $unit->save();

  // Deluxe type.
  $bat_type_2 = bat_type_create(array(
    'type' => 'room',
    'name' => $name2,
    'status' => 1,
    'bookable' => 1,
    'created' => REQUEST_TIME,
    'uid' => $uid,
  ));

  // Bedrooms and Bathrooms.
  $bat_type_2->field_st_max_capacity[LANGUAGE_NONE][0]['value'] = $capacity2;
  $bat_type_2->field_st_single_bed[LANGUAGE_NONE][0]['value'] = 2;
  $bat_type_2->field_st_double_bed[LANGUAGE_NONE][0]['value'] = 2;
  $bat_type_2->field_st_bedrooms[LANGUAGE_NONE][0]['value'] = 3;
  $bat_type_2->field_st_bathrooms[LANGUAGE_NONE][0]['value'] = 2;

  // Default Price.
  $bat_type_2->field_st_default_price[LANGUAGE_NONE][0] = array(
    'amount' => $price2,
    'currency_code' => 'USD',
    'data' => array(
      'components' => array(),
    ),
  );

  // Description.
  $bat_type_2->field_st_description[LANGUAGE_NONE][0]['value'] = 'A description of your vacation rental and the story behind it. Use the very first phrase to capture peoples imagination with an interesting fact such as "This house dates back to the 17th century when it was the summer home of Lord Byron".';

  // Gallery.
  for ($i = 0; $i <= 3; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder2 . '/default_' . $i . '.jpg');
    // Create managed File object and associate with Image field.
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Image title',
      'alt' => 'this is a description of the image.'
    );

    // Save the file to the root of the files directory.
    $default_image = file_copy($default_image, roomify_system_file_dir());
    $bat_type_2->field_st_gallery[LANGUAGE_NONE][$i] = (array) $default_image;
  }

  // Amenities.
  for ($i = 1; $i <= 14; $i++) {
    $bat_type_2->field_st_amenities[LANGUAGE_NONE][$i]['tid'] = $i;
  }

  // Save Type.
  bat_type_save($bat_type_2);

  // Create a unit.
  $unit = bat_unit_create(array('type' => 'default'));
  $unit->name = $name2 . ' 1';
  $unit->created = !empty($unit->date) ? strtotime($unit->date) : REQUEST_TIME;

  $unit->type_id = $bat_type_2->type_id;
  $unit->default_state = 1;
  $unit->uid = $uid;
  $unit->save();

  return array($bat_type_1->type_id, $bat_type_2->type_id);
}

/**
 * Create "Locanda Vivaldi" property.
 */
function roomify_example_content_create_locanda_vivaldi_example_property($type_ids, $capacity, $images_folder, $owner, $property_name = 'Locanda Vivaldi') {
  $module_path = drupal_get_path('module', 'roomify_accommodation_example_content');

  $property_type = roomify_property_create(array(
    'type' => 'locanda_property',
    'name' => $property_name,
    'created' => REQUEST_TIME,
    'language' => 'en',
  ));

  // Property Description.
  $property_type->field_sp_description['en'][0]['value'] = '<p>This refined hotel, overlooking St Mark\'s Basin, is a 4-minute walk from the Bridge of Sighs, a 5-minute walk from the Doge\'s Palace and a 7-minute walk from St Mark\'s Basilica.</p><p>Elegant rooms feature traditional, ornate Venetian decor and come with satellite TV and minibars. Some include exposed beamed ceilings and balconies, and upgraded rooms add whirlpool baths, separate sitting rooms and views of St Mark\'s Basin.</p><p>The hotel offers free continental breakfast. There\'s a rooftop terrace with a summertime restaurant, plus a bar.</p>';
  $property_type->field_sp_description['en'][0]['format'] = 'filtered_text';

  // Property Short Description.
  $property_type->field_sp_short_description['en'][0]['value'] = 'A great destination for every season';

  // Search/Featured Image.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_0.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_featured_image[LANGUAGE_NONE][0] = (array) $default_image;

  // Image Gallery.
  for ($i = 0; $i <= 2; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_' . $i . '.jpg');
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Venice',
      'alt' => 'Arrive in style'
    );
    $default_image = file_copy($default_image, roomify_system_file_dir());
    $property_type->field_sp_gallery['en'][$i] = (array) $default_image;
  }

  // Policies.
  $property_type->field_sp_policies['en'][0]['value'] = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

  // Highlight Title.
  $property_type->field_sp_highlight_title['en'][0]['value'] = 'Locanda Vivaldi';

  // Highlight Intro.
  $property_type->field_sp_highlight_intro['en'][0]['value'] = 'Visit the town Vivaldi was born in this amazing boutique hotel right in the centre of the historical city.';

  // Highlight Image 1.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_3.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image1[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 1 Caption.
  $property_type->field_sp_highlight_image1_cap['en'][0]['value'] = 'You wouldn\'t think you would find a swimming pool in Venice. But we got it done.';

  // Highlight Image 2.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_1.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image2[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 2 Caption.
  $property_type->field_sp_highlight_image2_cap['en'][0]['value'] = 'All the best comforts will make your stay special.';

  // Highlight Image 3.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_2.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image3[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 3 Caption.
  $property_type->field_sp_highlight_image3_cap['en'][0]['value'] = 'Enjoy meals at our wonderful traditional trattoria.';

  // Area.
  foreach (variable_get('roomify_accommodation_example_content_location_tids', array()) as $tid) {
    $property_type->field_sp_area[LANGUAGE_NONE][]['tid'] = $tid;
  }

  // Location.
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geom'] = 'POINT (14.8466491 36.7277406)';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geo_type'] = 'point';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['lat'] = '36.727740610900';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['lon'] = '14.846649169900';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['left'] = '14.846649169900';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['right'] = '14.846649169900';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['top'] = '36.727740610900';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['bottom'] = '36.727740610900';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geohash'] = 'sqd8cy4fxgpfxurv';

  // How to reach the Place.
  $property_type->field_sp_how_to_reach['en'][0]['value'] = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

  // Essentials Nearby.
  $property_type->field_sp_essentials['en'][0]['value'] = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

  foreach ($type_ids as $type_id) {
    $property_type->property_bat_type_reference[LANGUAGE_NONE][]['target_id'] = $type_id;
  }

  $user = user_load_by_name($owner);
  $property_type->uid = $user->uid;
  $property_type->field_sp_owner[LANGUAGE_NONE][0]['target_id'] = $user->uid;

  $property_type->save();

  foreach ($type_ids as $type_id) {
    $type = bat_type_load($type_id);
    $type->field_st_property_reference[LANGUAGE_NONE][0]['target_id'] = $property_type->property_id;
    $type->save();
  }

  return $property_type->property_id;
}

/**
 * Create "Miles Boutique Hotel" property.
 */
function roomify_example_content_create_miles_boutique_hotel_example_property($type_ids, $capacity, $images_folder, $owner) {
  $module_path = drupal_get_path('module', 'roomify_accommodation_example_content');

  $property_type = roomify_property_create(array(
    'type' => 'locanda_property',
    'name' => 'Miles Boutique Hotel',
    'created' => REQUEST_TIME,
    'language' => 'en',
  ));

  // Property Description.
  $property_type->field_sp_description['en'][0]['value'] = 'Situated on the banks of a Lake, The Castle of Cecil, by its remarkable state of preservation, the monument is one of the finest medieval castles in France and Europe built in the 15 th century by the Dukes of Anjou. The castle is amazingly compact architecturally, it completely surrounded by the River of Rhone. The Chateau is quite a apprehension sight, with unarticulated walls barely pierced to let the light in. The wall and towers, surrounded by a lush landscape and water, are the same height adding further to the solid appearance.';
  $property_type->field_sp_description['en'][0]['format'] = 'filtered_text';

  // Property Short Description.
  $property_type->field_sp_short_description['en'][0]['value'] = 'This is a headline for this beautiful rental';

  // Search/Featured Image.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_0.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_featured_image[LANGUAGE_NONE][0] = (array) $default_image;

  // Image Gallery.
  for ($i = 0; $i <= 3; $i++) {
    $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_' . $i . '.jpg');
    $default_image = (object) array(
      'uid' => 1,
      'uri' => $default,
      'filemime' => file_get_mimetype($default),
      'status' => 1,
      'title' => 'Image title',
      'alt' => 'this is a description of the image.'
    );
    $default_image = file_copy($default_image, roomify_system_file_dir());
    $property_type->field_sp_gallery['en'][$i] = (array) $default_image;
  }

  // Policies.
  $property_type->field_sp_policies['en'][0]['value'] = 'This is where you can define policies regarding the use of the accommodation such as pets, kids, check-in, check-out times, etc.';

  // Highlight Title.
  $property_type->field_sp_highlight_title['en'][0]['value'] = 'Miles Boutique Hotel';

  // Highlight Intro.
  $property_type->field_sp_highlight_intro['en'][0]['value'] = 'An amazing castle by a beautiful lake immersed in the French countryside. Eat, drink and be merry because this is a location that you will forever cherish.';

  // Highlight Image 1.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_1.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image1[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 1 Caption.
  $property_type->field_sp_highlight_image1_cap['en'][0]['value'] = 'Look at that cool thing on the table and the pillows on the couch.';

  // Highlight Image 2.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_2.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image2[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 2 Caption.
  $property_type->field_sp_highlight_image2_cap['en'][0]['value'] = 'It\'s a big blue couch. With lamps by the side. Nothing but the best for our castle.';

  // Highlight Image 3.
  $default = drupal_realpath($module_path . '/default_images/' . $images_folder . '/default_3.jpg');
  $default_image = (object) array(
    'uid' => 1,
    'uri' => $default,
    'filemime' => file_get_mimetype($default),
    'status' => 1,
  );
  $default_image = file_copy($default_image, roomify_system_file_dir());
  $property_type->field_sp_highlight_image3[LANGUAGE_NONE][0] = (array) $default_image;

  // Highlight Image 3 Caption.
  $property_type->field_sp_highlight_image3_cap['en'][0]['value'] = 'This time we went with a brown couch. Yellow seats on each side. A table in the middle. Boom.';

  // Area.
  foreach (variable_get('roomify_accommodation_example_content_location_tids', array()) as $tid) {
    $property_type->field_sp_area[LANGUAGE_NONE][]['tid'] = $tid;
  }

  // Location.
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geom'] = 'POINT (14.0181777 38.0364057)';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geo_type'] = 'point';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['lat'] = '37.460339242668';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['lon'] = '14.383013248444';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['left'] = '14.383013248444';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['right'] = '14.383013248444';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['top'] = '37.460339242668';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['bottom'] = '37.460339242668';
  $property_type->field_sp_location[LANGUAGE_NONE][0]['geohash'] = 'sqdjp73qk3rgxyrv';

  // How to reach the Place.
  $property_type->field_sp_how_to_reach['en'][0]['value'] = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

  // Essentials Nearby.
  $property_type->field_sp_essentials['en'][0]['value'] = 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.';

  foreach ($type_ids as $type_id) {
    $property_type->property_bat_type_reference[LANGUAGE_NONE][]['target_id'] = $type_id;
  }

  $user = user_load_by_name($owner);
  $property_type->uid = $user->uid;
  $property_type->field_sp_owner[LANGUAGE_NONE][0]['target_id'] = $user->uid;

  $property_type->save();

  foreach ($type_ids as $type_id) {
    $type = bat_type_load($type_id);
    $type->field_st_property_reference[LANGUAGE_NONE][0]['target_id'] = $property_type->property_id;
    $type->save();
  }

  return $property_type->property_id;
}

/**
 * Create example User.
 */
function roomify_example_user($name, $pass, $roles) {
  if ($account = user_load_by_name($name)) {
    return $account;
  }

  // Set up the user fields.
  $fields = array(
    'name' => $name,
    'mail' => 'webmaster+' . $name . '@roomify.us',
    'pass' => $pass,
    'status' => 1,
    'init' => 'email address',
    'roles' => $roles,
  );

  // The first parameter is left blank so a new user is created.
  $account = user_save('', $fields);

  return $account;
}

/**
 * Create user Profile2.
 */
function roomify_example_user_profile($uid) {
  $profile = profile2_create(array('uid' => $uid, 'type' => 'property_owner'));
  $profile->property_owner_name['en'][0]['value'] = 'Property owner';
  $profile->property_owner_bio['en'][0]['value'] = 'Example Bio';
  $profile->property_owner_short_info['en'][0]['value'] = 'This is an example of owner';

  $image_file = file_get_contents(drupal_get_path('module', 'roomify_accommodation_example_content') . '/default_images/homepage/santorini2.jpg');
  $image_file = file_save_data($image_file, roomify_system_file_dir() . 'owner.jpg', FILE_EXISTS_RENAME);

  $profile->property_owner_image[LANGUAGE_NONE][0] = array(
    'fid' => $image_file->fid,
    'filename' => $image_file->filename,
    'filemime' => $image_file->filemime,
    'uid' => $uid,
    'uri' => $image_file->uri,
    'status' => 1,
    'display' => 1,
  );

  $profile->property_owner_google_page[LANGUAGE_NONE][0]['url'] = 'http://www.plus.google.com';
  $profile->property_owner_youtube_page[LANGUAGE_NONE][0]['url'] = 'http://www.youtube.com';
  $profile->property_owner_pinterest_page[LANGUAGE_NONE][0]['url'] = 'http://www.pinterest.com';
  $profile->property_owner_instagram_page[LANGUAGE_NONE][0]['url'] = 'http://www.instagram.com';
  $profile->property_owner_twitter_page[LANGUAGE_NONE][0]['url'] = 'http://www.twitter.com';
  $profile->property_owner_facebook_page[LANGUAGE_NONE][0]['url'] = 'http://www.facebook.com';

  $profile->save();
}

/**
 * Create example Conversation.
 */
function roomify_example_content_create_conversation($start_date, $end_date, $property_id, $type_id, $guest) {
  $property = roomify_property_load($property_id);
  $type = bat_type_load($type_id);

  $conv_fields = array(
    'name' => 'Conversation with ' . $guest->name,
    'type' => 'standard',
    'created' => REQUEST_TIME,
    'changed' => REQUEST_TIME,
    'uid' => $guest->uid,
    'language' => LANGUAGE_NONE,
  );

  $conversation = roomify_conversation_create($conv_fields);

  $conversation->conversation_unit_type_ref[LANGUAGE_NONE][0]['target_id'] = $type_id;
  $conversation->conversation_guest_user_ref[LANGUAGE_NONE][0]['target_id'] = $guest->uid;
  $conversation->conversation_owner_user_ref[LANGUAGE_NONE][0]['target_id'] = $property->uid;
  $conversation->conversation_book_start_date[LANGUAGE_NONE][0]['value'] = $start_date->format('Y-m-d');
  $conversation->conversation_book_end_date[LANGUAGE_NONE][0]['value'] = $end_date->format('Y-m-d');
  $conversation->conversation_user_name[LANGUAGE_NONE][0]['value'] = $guest->name;
  $conversation->conversation_book_price[LANGUAGE_NONE][0] = array(
    'amount' => '10000',
    'currency_code' => 'USD',
    'data' => array(
      'components' => array(),
    ),
  );
  $conversation->conversation_guests[LANGUAGE_NONE][0]['value'] = 2;
  $conversation->conversation_user_email[LANGUAGE_NONE][0]['value'] = $guest->mail;
  $conversation->conversation_further_info[LANGUAGE_NONE][0]['value'] = 'test test';

  $conversation->save();

  return $conversation->conversation_id;
}

/**
 * Example content for "Vacation Rental".
 */
function roomify_accommodation_example_content_vacation_rental() {
  $account = roomify_accommodation_example_content_get_manager_account();

  roomify_accommodation_example_create_example_location_terms();

  $type_id = roomify_example_content_create_casa_example_type('My Vacation Rental', 6, 'casa_sul_mare', $account->uid);
  $property_id = roomify_example_content_create_casa_sul_mare_example_property($type_id, 'casa_sul_mare', $account->name, 'My Vacation Rental');

  variable_set('site_frontpage', 'listing/' . $property_id);
  variable_set('site_name', 'My Vacation Rental');

  variable_set('roomify_accommodation_example_content', 'vacation_rental');
  variable_set('roomify_accommodation_example_content_property_id', $property_id);

  cache_clear_all('*', 'cache_page', TRUE);
}

/**
 * Example content for "B&B".
 */
function roomify_accommodation_example_content_b_and_b() {
  $account = roomify_accommodation_example_content_get_manager_account();

  roomify_accommodation_example_create_example_location_terms();

  $type_ids = roomify_example_content_create_example_types('The Doges Rooms', 4, 'locanda1', '10000', 'Vivaldi Suite', 2, 'locanda2', '10000', $account->uid);
  $property_id = roomify_example_content_create_locanda_vivaldi_example_property($type_ids, 5, 'locanda2', $account->name, 'My B&B / Hotel');

  variable_set('site_frontpage', 'listing/' . $property_id);
  variable_set('site_name', 'My B&B / Hotel');

  variable_set('roomify_accommodation_example_content', 'b_and_b');
  variable_set('roomify_accommodation_example_content_property_id', $property_id);

  cache_clear_all('*', 'cache_page', TRUE);
}

/**
 * Example content for "Multi-property".
 */
function roomify_accommodation_example_content_multi_property() {
  roomify_accommodation_example_create_example_location_terms();

  // Create Roles for Guests.
  $guest_role = user_role_load_by_name('guest');
  $guest_rid = $guest_role->rid;

  $guest_roles = array(
    DRUPAL_AUTHENTICATED_RID => 'authenticated user',
    $guest_rid => TRUE,
  );

  // Create Roles for Property Owners.
  $property_owner_role = user_role_load_by_name('property owner');
  $property_owner_rid = $property_owner_role->rid;

  $property_owner_roles = array(
    DRUPAL_AUTHENTICATED_RID => 'authenticated user',
    $property_owner_rid => TRUE,
  );

  // Creates Some Users (Guests and Property Owners).
  $guest1 = roomify_example_user('guest1', 'guest1', $guest_roles);
  $guest2 = roomify_example_user('guest2', 'guest2', $guest_roles);
  $guest3 = roomify_example_user('guest3', 'guest3', $guest_roles);
  $guest4 = roomify_example_user('guest4', 'guest4', $guest_roles);
  $property1 = roomify_example_user('property1', 'property1', $property_owner_roles);
  $property2 = roomify_example_user('property2', 'property2', $property_owner_roles);

  roomify_example_user_profile($property1->uid);
  roomify_example_user_profile($property2->uid);

  // CASA EXAMPLE CONTENT.

  // Create Example Casa type.
  $type_id = roomify_example_content_create_casa_example_type('Casa Sul Mare', 6, 'casa_sul_mare', $property1->uid, '2000');

  // Create Example Casa property.
  $property_id_1 = roomify_example_content_create_casa_sul_mare_example_property($type_id, 'casa_sul_mare', 'property1');

  // Create Another.
  $type_id = roomify_example_content_create_casa_example_type('Casa Azzurra', 11, 'casa_azzurra', $property2->uid, '1500');

  // Create Example Casa property.
  $property_id_2 = roomify_example_content_create_casa_azzurra_example_property($type_id, 'casa_azzurra', 'property2');

  // LOCANDA EXAMPLE CONTENT.

  // Create Example Locanda types.
  $type_ids = roomify_example_content_create_example_types('Standard', 4, 'locanda1', '10000', 'Deluxe', 5, 'locanda2', '12000', $property1->uid);

  // Create Example Locanda property.
  $property_id_3 = roomify_example_content_create_miles_boutique_hotel_example_property($type_ids, 4, 'locanda1', 'property1');

  // Create Example Locanda types.
  $type_ids = roomify_example_content_create_example_types('The Doges Rooms', 4, 'locanda1', '15000', 'Vivaldi Suite', 2, 'locanda2', '13000', $property2->uid);

  // Create Example Locanda property.
  $property_id_4 = roomify_example_content_create_locanda_vivaldi_example_property($type_ids, 5, 'locanda2', 'property2');

  // EXAMPLE CONVERSATIONS.

  $properties = roomify_property_load_multiple(FALSE, array('name' => array('Casa sul mare', 'Casa Azzurra', 'Miles Boutique Hotel', 'Locanda Vivaldi')));

  $start_date = new DateTime();
  $start_date->add(new DateInterval('P5D'));
  $start_date->setTime(0, 0);

  $end_date = new DateTime();
  $end_date->add(new DateInterval('P12D'));
  $end_date->setTime(0, 0);

  $first_property = array_shift($properties);
  $last_property = array_pop($properties);
  $first_type = $first_property->property_bat_type_reference[LANGUAGE_NONE][0]['target_id'];
  $last_type = $last_property->property_bat_type_reference[LANGUAGE_NONE][0]['target_id'];

  $conversation_id_1 = roomify_example_content_create_conversation($start_date, $end_date, $first_property->property_id, $first_type, $guest3);
  $conversation_id_2 = roomify_example_content_create_conversation($start_date, $end_date, $last_property->property_id, $last_type, $guest4);

  // Create a location node to show in the map.
  roomify_example_content_create_location_example_node();

  if (module_exists('roomify_properties_list')) {
    $properties_list_nodes = roomify_example_content_create_properties_list_node($property_id_1, $property_id_2, $property_id_3);
  }
  // Create Homepage.
  variable_set('roomify_accommodation_example_content', 'multi_property');
  roomify_example_content_create_homepage_node($property_id_1, $property_id_2, $property_id_3);

  $property_ids = array(
    $property_id_1 => 'Casa Sul Mare',
    $property_id_2 => 'Casa Azzurra',
    $property_id_3 => 'Miles Boutique Hotel',
    $property_id_4 => 'Locanda Vivaldi',
  );
  $conversation_ids = array(
    $conversation_id_1,
    $conversation_id_2,
  );

  variable_set('roomify_accommodation_example_content_property_id', $property_ids);
  variable_set('roomify_accommodation_example_content_conversation_id', $conversation_ids);

  cache_clear_all('*', 'cache_page', TRUE);
}

/**
 * Remove example content for "Vacation Rental".
 */
function roomify_accommodation_example_content_vacation_rental_delete() {
  $property = roomify_property_load(variable_get('roomify_accommodation_example_content_property_id'));

  foreach ($property->property_bat_type_reference[LANGUAGE_NONE] as $type) {
    $bat_type = bat_type_load($type['target_id']);
    $bat_type->delete();

    // Delete all related Conversations.
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'roomify_conversation')
      ->fieldCondition('conversation_unit_type_ref', 'target_id', $type['target_id'], '=');
    $result = $query->execute();

    if (isset($result['roomify_conversation'])) {
      foreach ($result['roomify_conversation'] as $cid) {
        roomify_conversation_delete_multiple(array($cid->conversation_id));
      }
    }
  }

  $property->delete();

  entity_delete_multiple('taxonomy_term', variable_get('roomify_accommodation_example_content_location_tids', array()));

  variable_del('roomify_accommodation_example_content');
  variable_del('roomify_accommodation_example_content_location_tids');
  variable_set('roomify_accommodation_example_content_property_id', '');
  variable_set('site_frontpage', 'node');
  variable_set('site_name', 'Roomify');

  cache_clear_all('*', 'cache_page', TRUE);
}

/**
 * Remove example content for "B&B / Hotel".
 */
function roomify_accommodation_example_content_b_and_b_delete() {
  $property = roomify_property_load(variable_get('roomify_accommodation_example_content_property_id'));

  foreach ($property->property_bat_type_reference[LANGUAGE_NONE] as $type) {
    $bat_type = bat_type_load($type['target_id']);
    $bat_type->delete();

    // Delete all related Conversations.
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'roomify_conversation')
      ->fieldCondition('conversation_unit_type_ref', 'target_id', $type['target_id'], '=');
    $result = $query->execute();

    if (isset($result['roomify_conversation'])) {
      foreach ($result['roomify_conversation'] as $cid) {
        roomify_conversation_delete_multiple(array($cid->conversation_id));
      }
    }
  }

  $property->delete();

  entity_delete_multiple('taxonomy_term', variable_get('roomify_accommodation_example_content_location_tids', array()));

  variable_del('roomify_accommodation_example_content');
  variable_del('roomify_accommodation_example_content_location_tids');
  variable_set('roomify_accommodation_example_content_property_id', '');
  variable_set('site_frontpage', 'node');
  variable_set('site_name', 'Roomify');

  cache_clear_all('*', 'cache_page', TRUE);
}

/**
 * Remove example content for "Multi-property".
 */
function roomify_accommodation_example_content_multi_property_delete($type_delete) {
  // Delete all example properties.
  $property_ids = variable_get('roomify_accommodation_example_content_property_id', array());

  foreach ($property_ids as $property_id => $property_name) {
    if ($property = roomify_property_load($property_id)) {

      if ($type_delete['property_' . $property_id]) {
        foreach ($property->property_bat_type_reference[LANGUAGE_NONE] as $type) {
          $bat_type = bat_type_load($type['target_id']);
          $bat_type->delete();

          // Delete all related Conversations.
          $query = new EntityFieldQuery();
          $query->entityCondition('entity_type', 'roomify_conversation')
            ->fieldCondition('conversation_unit_type_ref', 'target_id', $type['target_id'], '=');
          $result = $query->execute();

          if (isset($result['roomify_conversation'])) {
            foreach ($result['roomify_conversation'] as $cid) {
              roomify_conversation_delete_multiple(array($cid->conversation_id));
            }
          }
        }

        $property->delete();
      }
    }
  }

  // Delete all example conversations.
  if ($type_delete['conversations']) {
    $conversation_ids = variable_get('roomify_accommodation_example_content_conversation_id', array());

    foreach ($conversation_ids as $conversation_id) {
      if ($conversation = roomify_conversation_load($conversation_id)) {
        $conversation->delete();
      }
    }
  }

  // Delete all example users.
  if ($type_delete['users']) {
    if ($guest1 = user_load_by_name('guest1')) {
      user_delete($guest1->uid);
    }

    if ($guest2 = user_load_by_name('guest2')) {
      user_delete($guest2->uid);
    }

    if ($guest3 = user_load_by_name('guest3')) {
      user_delete($guest3->uid);
    }

    if ($guest4 = user_load_by_name('guest4')) {
      user_delete($guest4->uid);
    }

    if ($property1 = user_load_by_name('property1')) {
      user_delete($property1->uid);
    }

    if ($property2 = user_load_by_name('property2')) {
      user_delete($property2->uid);
    }
  }
  if ($type_delete['homepage']) {
    // Delete all Homepage nodes.
    $node_types = array('homepage');
    $query = new EntityFieldQuery();
    $query->entityCondition('entity_type', 'node')
      ->propertyCondition('type', $node_types, 'IN');
    $result = $query->execute();
    foreach ($result['node'] as $node) {
      node_delete($node->nid);
    }

    module_disable(array('roomify_homepage'));
    drupal_uninstall_modules(array('roomify_homepage'));
  }

  entity_delete_multiple('taxonomy_term', variable_get('roomify_accommodation_example_content_location_tids', array()));

  variable_del('roomify_accommodation_example_content');
  variable_del('roomify_accommodation_example_content_property_id');
  variable_del('roomify_accommodation_example_content_conversation_id');
  variable_del('roomify_accommodation_example_content_location_tids');

  cache_clear_all('*', 'cache_page', TRUE);
}

/**
 * Create or Remove example content form.
 */
function roomify_accommodation_example_content_manage_form($form, &$form_state) {
  $form['example_content'] = array(
    '#type' => 'fieldset',
    '#title' => t('Install example content'),
  );

  $form['example_content']['vacation_rental'] = array(
    '#type' => 'submit',
    '#value' => t('Setup as Vacation Rental'),
    '#submit' => array('roomify_accommodation_example_content_manage_form_vacation_rental_submit'),
    '#description' => t('This will setup Roomify for Accommodations as a vacation rental site setting the site homepage to your Vacation Rental description.'),
    '#attributes' => array('style' => 'display: block; width: 250px;'),
  );

  $form['example_content']['b_and_b'] = array(
    '#type' => 'submit',
    '#value' => t('Setup as B&B / Hotel'),
    '#submit' => array('roomify_accommodation_example_content_manage_form_b_and_b_submit'),
    '#description' => t('This will setup Roomify for Accommodations as a b&b / hotel site setting the site homepage to your b&b / hotel description.'),
    '#attributes' => array('style' => 'display: block; width: 250px;'),
  );

  $form['example_content']['multi_property'] = array(
    '#type' => 'submit',
    '#value' => t('Setup as Multi-property'),
    '#submit' => array('roomify_accommodation_example_content_manage_form_multi_property_submit'),
    '#description' => t('This will setup Roomify for Accommodations as a multi property site.'),
    '#attributes' => array('style' => 'display: block; width: 250px;'),
  );

  $installed_type = variable_get('roomify_accommodation_example_content');

  switch ($installed_type) {
    case 'vacation_rental':
      $form['example_content']['vacation_rental']['#value'] = t('Delete Vacation Rental Setup');
      $form['example_content']['b_and_b']['#disabled'] = TRUE;
      $form['example_content']['multi_property']['#disabled'] = TRUE;
      break;

    case 'b_and_b':
      $form['example_content']['b_and_b']['#value'] = t('Delete B&B / Hotel Setup');
      $form['example_content']['vacation_rental']['#disabled'] = TRUE;
      $form['example_content']['multi_property']['#disabled'] = TRUE;
      break;

    case 'multi_property':
      $form['example_content']['multi_property']['#value'] = t('Delete Multi-property Setup');
      $form['example_content']['vacation_rental']['#disabled'] = TRUE;
      $form['example_content']['b_and_b']['#disabled'] = TRUE;
      break;
  }

  return $form;
}

/**
 * Create or Remove "Vacation Rental" example content.
 */
function roomify_accommodation_example_content_manage_form_vacation_rental_submit($form, &$form_state) {
  if (isset($_GET['destination'])) {
    unset($_GET['destination']);
  }

  $installed_type = variable_get('roomify_accommodation_example_content');

  if ($installed_type == 'vacation_rental') {
    $form_state['redirect'] = 'admin/bat/config/example-content/delete';
  }
  else {
    $operations = array();
    $operations[] = array(
      'roomify_accommodation_example_content_vacation_rental',
      array(),
    );

    $batch = array(
      'operations' => $operations,
    );
    batch_set($batch);
  }
}

/**
 * Create or Remove "B&B / Hotel" example content.
 */
function roomify_accommodation_example_content_manage_form_b_and_b_submit($form, &$form_state) {
  if (isset($_GET['destination'])) {
    unset($_GET['destination']);
  }

  $installed_type = variable_get('roomify_accommodation_example_content');

  if ($installed_type == 'b_and_b') {
    $form_state['redirect'] = 'admin/bat/config/example-content/delete';
  }
  else {
    $operations = array();
    $operations[] = array(
      'roomify_accommodation_example_content_b_and_b',
      array(),
    );

    $batch = array(
      'operations' => $operations,
    );
    batch_set($batch);
  }
}

/**
 * Create or Remove "Multi-property" example content.
 */
function roomify_accommodation_example_content_manage_form_multi_property_submit($form, &$form_state) {
  if (isset($_GET['destination'])) {
    unset($_GET['destination']);
  }

  $installed_type = variable_get('roomify_accommodation_example_content');

  if ($installed_type == 'multi_property') {
    $form_state['redirect'] = 'admin/bat/config/example-content/delete';
  }
  else {
    $operations = array();
    $operations[] = array(
      'roomify_accommodation_example_content_multi_property',
      array(),
    );

    $batch = array(
      'operations' => $operations,
    );
    batch_set($batch);
  }
}

/**
 * Delete form.
 */
function roomify_accommodation_example_content_delete_form($form, &$form_state) {
  $installed_type = variable_get('roomify_accommodation_example_content');

  if ($installed_type == 'multi_property') {
    $property_ids = variable_get('roomify_accommodation_example_content_property_id', array());

    $form['type_delete'] = array(
      '#type' => 'fieldset',
      '#title' => t('Choose which content you want to delete'),
      '#tree' => TRUE,
    );

    foreach ($property_ids as $property_id => $property_name) {
      if ($property = roomify_property_load($property_id)) {
        $form['type_delete']['property_' . $property_id] = array(
          '#type' => 'checkbox',
          '#title' => t('Remove property "@property_name"', array('@property_name' => $property->name)),
          '#default_value' => 1,
        );
      }
    }

    $form['type_delete']['users'] = array(
      '#type' => 'checkbox',
      '#title' => t('Remove example Users'),
      '#default_value' => 1,
    );

    $form['type_delete']['conversations'] = array(
      '#type' => 'checkbox',
      '#title' => t('Remove example Conversations'),
      '#default_value' => 1,
    );

    if (module_exists('roomify_accommodation_example_bookings')) {
      $form['type_delete']['bookings'] = array(
        '#type' => 'checkbox',
        '#title' => t('Remove example Bookings'),
        '#default_value' => 1,
      );
    }
    if (module_exists('roomify_homepage')) {
      $form['type_delete']['homepage'] = array(
        '#type' => 'checkbox',
        '#title' => t('Remove Roomify Homepage'),
        '#default_value' => 1,
      );
    }
  }

  return confirm_form(
    $form,
    t('Remove example content'),
    'admin/bat/config/example-content',
    t('This action cannot be undone. Are you sure you want to proceed?')
  );
}

/**
 * Submit callback for the roomify_accommodation_example_content_delete_form form.
 */
function roomify_accommodation_example_content_delete_form_submit($form, &$form_state) {
  $installed_type = variable_get('roomify_accommodation_example_content');

  if ($installed_type == 'vacation_rental') {
    $operations = array();
    $operations[] = array(
      'roomify_accommodation_example_content_vacation_rental_delete',
      array(),
    );

    $batch = array(
      'operations' => $operations,
    );
    batch_set($batch);
  }
  elseif ($installed_type == 'b_and_b') {
    $operations = array();
    $operations[] = array(
      'roomify_accommodation_example_content_b_and_b_delete',
      array(),
    );

    $batch = array(
      'operations' => $operations,
    );
    batch_set($batch);
  }
  elseif ($installed_type == 'multi_property') {
    $operations = array();
    $operations[] = array(
      'roomify_accommodation_example_content_multi_property_delete',
      array($form_state['values']['type_delete']),
    );

    $batch = array(
      'operations' => $operations,
    );
    batch_set($batch);
  }

  $form_state['redirect'] = 'admin/bat/config/example-content';
}

/**
 * Helper function - return roomify manager account if present, otherwise
 * return user 1 account.
 */
function roomify_accommodation_example_content_get_manager_account() {
  global $user;

  if ($user->uid == 0) {
    $role = user_role_load_by_name('roomify manager');
    $query = 'SELECT ur.uid
              FROM {users_roles} AS ur
              WHERE ur.rid = :rid';
    $result = db_query($query, array(':rid' => $role->rid));
    $uids = $result->fetchCol();
    if (count($uids)) {
      $account = user_load(current($uids));
    }
    else {
      $account = user_load(1);
    }
  }
  else {
    $account = $user;
  }

  return $account;
}

/**
 * Creates Area example terms.
 */
function roomify_accommodation_example_create_example_location_terms() {
  $module_path = drupal_get_path('module', 'roomify_accommodation_example_content');

  $vocabulary = taxonomy_vocabulary_machine_name_load('location');

  $image1_url = drupal_realpath($module_path . '/default_images/areas/taormina.jpg');
  $image1 = (object) array(
    'uid' => 1,
    'uri' => $image1_url,
    'filemime' => file_get_mimetype($image1_url),
    'status' => 1,
  );
  $image1 = file_copy($image1, roomify_system_file_dir());

  $taormina1_url = drupal_realpath($module_path . '/default_images/areas/taormina_1.jpg');
  $taormina1 = (object) array(
    'uid' => 1,
    'uri' => $taormina1_url,
    'filemime' => file_get_mimetype($taormina1_url),
    'status' => 1,
  );
  $taormina1 = file_copy($taormina1, roomify_system_file_dir());

  $taormina2_url = drupal_realpath($module_path . '/default_images/areas/taormina_2.jpg');
  $taormina2 = (object) array(
    'uid' => 1,
    'uri' => $taormina2_url,
    'filemime' => file_get_mimetype($taormina2_url),
    'status' => 1,
  );
  $taormina2 = file_copy($taormina2, roomify_system_file_dir());

  $image2_url = drupal_realpath($module_path . '/default_images/areas/cefalu.jpg');
  $image2 = (object) array(
    'uid' => 1,
    'uri' => $image2_url,
    'filemime' => file_get_mimetype($image2_url),
    'status' => 1,
  );
  $image2 = file_copy($image2, roomify_system_file_dir());

  $cefalu1_url = drupal_realpath($module_path . '/default_images/areas/cefalu_1.jpg');
  $cefalu1 = (object) array(
    'uid' => 1,
    'uri' => $cefalu1_url,
    'filemime' => file_get_mimetype($cefalu1_url),
    'status' => 1,
  );
  $cefalu1 = file_copy($cefalu1, roomify_system_file_dir());

  $cefalu2_url = drupal_realpath($module_path . '/default_images/areas/cefalu_2.jpg');
  $cefalu2 = (object) array(
    'uid' => 1,
    'uri' => $cefalu2_url,
    'filemime' => file_get_mimetype($cefalu2_url),
    'status' => 1,
  );
  $cefalu2 = file_copy($cefalu2, roomify_system_file_dir());

  $image3_url = drupal_realpath($module_path . '/default_images/areas/san_vito.jpg');
  $image3 = (object) array(
    'uid' => 1,
    'uri' => $image3_url,
    'filemime' => file_get_mimetype($image3_url),
    'status' => 1,
  );
  $image3 = file_copy($image3, roomify_system_file_dir());

  $san_vito1_url = drupal_realpath($module_path . '/default_images/areas/san_vito_1.jpg');
  $san_vito1 = (object) array(
    'uid' => 1,
    'uri' => $san_vito1_url,
    'filemime' => file_get_mimetype($san_vito1_url),
    'status' => 1,
  );
  $san_vito1 = file_copy($san_vito1, roomify_system_file_dir());

  $san_vito2_url = drupal_realpath($module_path . '/default_images/areas/san_vito_2.jpg');
  $san_vito2 = (object) array(
    'uid' => 1,
    'uri' => $san_vito2_url,
    'filemime' => file_get_mimetype($san_vito2_url),
    'status' => 1,
  );
  $san_vito2 = file_copy($san_vito2, roomify_system_file_dir());

  $description = '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>';

  $term1 = new stdClass();
  $term1->name = 'Taormina';
  $term1->field_area_featured_image[LANGUAGE_NONE][0] = (array) $image1;
  $term1->description = $description;
  $term1->description_field['en'][0]['value'] = $description;
  $term1->description_field['en'][0]['format'] = 'filtered_text';
  $term1->description_field[LANGUAGE_NONE][0]['value'] = $description;
  $term1->description_field[LANGUAGE_NONE][0]['format'] = 'filtered_text';

  $term1->field_area_description_subtitle['en'][0]['value'] = 'a charming hillside town on the east coast of Sicily';

  $term1->field_title_featured_properties['en'][0]['value'] = 'Featured Properties';

  $term1->field_area_title_description['en'][0]['value'] = 'Taormina';

  // Gallery.
  $gallery = new ParagraphsItemEntity(array('field_name' => 'field_area_slideshow', 'bundle' => 'slideshow'));
  $gallery->is_new = TRUE;
  $gallery->field_cta_title[LANGUAGE_NONE][0]['value'] = 'Taormina';
  $gallery->field_cta_gallery_size[LANGUAGE_NONE][0]['value'] = '1';
  $gallery->field_cta_gallery[LANGUAGE_NONE][0] = array(
    'fid' => $taormina1->fid,
    'filename' => $taormina1->filename,
    'filemime' => $taormina1->filemime,
    'uid' => 1,
    'uri' => $taormina1->uri,
    'status' => 1,
    'display' => 1,
  );
  $gallery->field_cta_gallery[LANGUAGE_NONE][1] = array(
    'fid' => $taormina2->fid,
    'filename' => $taormina2->filename,
    'filemime' => $taormina2->filemime,
    'uid' => 1,
    'uri' => $taormina2->uri,
    'status' => 1,
    'display' => 1,
  );

  $term1->vid = $vocabulary->vid;
  taxonomy_term_save($term1);

  $gallery->setHostEntity('taxonomy_term', $term1);
  $gallery->save();

  $term2 = new stdClass();
  $term2->name = 'Cefalù';
  $term2->field_area_featured_image[LANGUAGE_NONE][0] = (array) $image2;
  $term2->description = $description;
  $term2->description_field['en'][0]['value'] = $description;
  $term2->description_field['en'][0]['format'] = 'filtered_text';
  $term2->description_field[LANGUAGE_NONE][0]['value'] = $description;
  $term2->description_field[LANGUAGE_NONE][0]['format'] = 'filtered_text';

  $term2->field_area_description_subtitle['en'][0]['value'] = 'a fishing village and popular beach resort on the north coast of Sicily';

  $term2->field_title_featured_properties['en'][0]['value'] = 'Featured Properties';

  $term2->field_area_title_description['en'][0]['value'] = 'Cefalù';

  // Gallery.
  $gallery = new ParagraphsItemEntity(array('field_name' => 'field_area_slideshow', 'bundle' => 'slideshow'));
  $gallery->is_new = TRUE;
  $gallery->field_cta_title[LANGUAGE_NONE][0]['value'] = 'Cefalù';
  $gallery->field_cta_gallery_size[LANGUAGE_NONE][0]['value'] = '1';
  $gallery->field_cta_gallery[LANGUAGE_NONE][0] = array(
    'fid' => $cefalu1->fid,
    'filename' => $cefalu1->filename,
    'filemime' => $cefalu1->filemime,
    'uid' => 1,
    'uri' => $cefalu1->uri,
    'status' => 1,
    'display' => 1,
  );
  $gallery->field_cta_gallery[LANGUAGE_NONE][1] = array(
    'fid' => $cefalu2->fid,
    'filename' => $cefalu2->filename,
    'filemime' => $cefalu2->filemime,
    'uid' => 1,
    'uri' => $cefalu2->uri,
    'status' => 1,
    'display' => 1,
  );

  $term2->vid = $vocabulary->vid;
  taxonomy_term_save($term2);
  $gallery->setHostEntity('taxonomy_term', $term2);
  $gallery->save();

  $term3 = new stdClass();
  $term3->name = 'San Vito lo Capo';
  $term3->field_area_featured_image[LANGUAGE_NONE][0] = (array) $image3;
  $term3->description = $description;
  $term3->description_field['en'][0]['value'] = $description;
  $term3->description_field['en'][0]['format'] = 'filtered_text';
  $term3->description_field[LANGUAGE_NONE][0]['value'] = $description;
  $term3->description_field[LANGUAGE_NONE][0]['format'] = 'filtered_text';

  $term3->field_area_description_subtitle['en'][0]['value'] = 'a charming seaside town on the west coast of Sicily';

  $term3->field_title_featured_properties['en'][0]['value'] = 'Featured Properties';

  $term3->field_area_title_description['en'][0]['value'] = 'San Vito lo Capo';

  // Gallery.
  $gallery = new ParagraphsItemEntity(array('field_name' => 'field_area_slideshow', 'bundle' => 'slideshow'));
  $gallery->is_new = TRUE;
  $gallery->field_cta_title[LANGUAGE_NONE][0]['value'] = 'San Vito lo Capo';
  $gallery->field_cta_gallery_size[LANGUAGE_NONE][0]['value'] = '1';
  $gallery->field_cta_gallery[LANGUAGE_NONE][0] = array(
    'fid' => $san_vito1->fid,
    'filename' => $san_vito1->filename,
    'filemime' => $san_vito1->filemime,
    'uid' => 1,
    'uri' => $san_vito1->uri,
    'status' => 1,
    'display' => 1,
  );
  $gallery->field_cta_gallery[LANGUAGE_NONE][1] = array(
    'fid' => $san_vito2->fid,
    'filename' => $san_vito2->filename,
    'filemime' => $san_vito2->filemime,
    'uid' => 1,
    'uri' => $san_vito2->uri,
    'status' => 1,
    'display' => 1,
  );

  $term3->vid = $vocabulary->vid;
  taxonomy_term_save($term3);

  $gallery->setHostEntity('taxonomy_term', $term3);
  $gallery->save();

  variable_set('roomify_accommodation_example_content_location_tids', array($term1->tid, $term2->tid, $term3->tid));
}
