<?php

/**
 * @file
 */

/**
 * Implements hook_ctools_plugin_api().
 */
function roomify_accommodations_group_dashboard_ctools_plugin_api($module = NULL, $api = NULL) {
  if ($module == "page_manager" && $api == "pages_default") {
    return array("version" => "1");
  }
  if ($module == "panels_mini" && $api == "panels_default") {
    return array("version" => "1");
  }
}

/**
 * Implements hook_module_implements_alter().
 */
function roomify_accommodations_group_dashboard_module_implements_alter(&$implementations, $hook) {
  if ($hook == 'menu_local_tasks_alter' && isset($implementations['roomify_accommodations_group_dashboard'])) {
    $group = $implementations['roomify_accommodations_group_dashboard'];
    unset($implementations['roomify_accommodations_group_dashboard']);
    $implementations['roomify_accommodations_group_dashboard'] = $group;
  }
}

/**
 * Implements hook_menu_local_tasks_alter().
 *
 * Move node creation local tasks to group/%group/content.
 */
function roomify_accommodations_group_dashboard_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  if ($root_path == 'group/%/content') {
    $gid = $router_item['original_map'][1];

    foreach (node_type_get_types() as $node_type => $info) {
      $item = menu_get_item("group/$gid/node/add/$node_type");

      // Add one general and one unique class for styling purposes.
      $item['localized_options']['attributes']['class'][] = 'group-local-action';
      $item['localized_options']['attributes']['class'][] = 'group-local-action-' . str_replace('_', '-', $node_type);

      // Add another class to target just Group Node local actions.
      $item['localized_options']['attributes']['class'][] = 'gnode-local-action';

      if ($item['access']) {
        $data['actions']['output'][] = array(
          '#theme' => 'menu_local_action',
          '#link' => $item,
        );
      }
    }
  }

  if ($root_path == 'group/%') {
    unset($data['actions']['output']);

    roomify_accommodations_group_menu_local_tasks_alter($data, $router_item, $root_path);
  }
}
